---
title: "Untitled"
author: "MLP"
date: "2023-09-21"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
rm(list = ls())
```


```{r}
BCRLJ_chainlong=read.csv("/home/maolp/Allcount/All_scanpyData/BCRTCRchain/BCRLJ_chainlong.csv")
```

```{r}
library(tidyverse)
library(scales)
library(ggplot2)
library(dplyr)
library(RColorBrewer )
library(ComplexHeatmap)
BCRLJ=BCRLJ_chainlong
```

```{r}
BCRLJVlist_values<-read.csv("TCRBCRchain200/j_call_B_VJ_main_list.csv")
```

```{r}
BCRLJ$variable<-factor(BCRLJ$variable,level=BCRLJVlist_values$x)
```


```{r}
library(dplyr)



split_BCRLJ<- strsplit(BCRLJ$Sample, "_")


BCRLJ$CellType <- sapply(split_BCRLJ, "[", 1)
BCRLJ$AdjusteID<- sapply(split_BCRLJ, "[", 2)

BCRLJ$Organ <- substr(BCRLJ$AdjusteID, 1, 1)
BCRLJ$Sample<-factor(BCRLJ$Sample,level=rev(sort(unique(BCRLJ$Sample))))
BCRLJ2 <- BCRLJ %>% group_by(variable) %>% filter(sum(as.numeric(value) )!= 0) %>%ungroup()
BCRLJ2$Week<-substring(BCRLJ2$AdjusteID,2,5) %>% as.numeric()
BCRLJ2$Stage<-ifelse(BCRLJ2$Week<=28,'Early','Late')


library(dplyr)

BCRLJ2 <- BCRLJ2 %>% 
  mutate(Organ = case_when(
    Organ == "B" ~ "PBMC",
    Organ == "L" ~ "Liver",
    Organ == "S" ~ "Spleen",
    Organ == "T" ~ "Thymus",
    TRUE ~ Organ  
  ))
BCRLJ2$Organ_Stage=paste0(BCRLJ2$Stage,'_',BCRLJ2$Organ)
```
```{r}
BCRLJ2$Organ_Stage<-factor(BCRLJ2$Organ_Stage,levels = c("Early_PBMC"  , "Late_PBMC",  "Early_Liver", "Early_Thymus" ,  "Early_Spleen" ))
```

```{r}
library(dplyr)
library(purrr)
library(ggpubr)
library(ggsci)
# Subset the data
data_subset <- subset(BCRLJ2, CellType == "IGKC+Naïve B")
my_comparisons <- list(
  c("Early_PBMC", "Late_PBMC"),
  c("Early_PBMC", "Early_Liver"),
  c("Early_PBMC", "Early_Spleen"),
  c("Early_PBMC", "Early_Thymus"),
  c("Late_PBMC", "Early_Liver"),
  c("Late_PBMC", "Early_Spleen"),
  c("Late_PBMC", "Early_Thymus"),
  c("Early_Liver", "Early_Spleen"),
  c("Early_Liver", "Early_Thymus"),
  c("Early_Spleen", "Early_Thymus")
)
P2A=subset(BCRLJ2,CellType=="IGKC+Naïve B") %>% ggplot(aes(Organ_Stage,value,fill=Organ_Stage))+geom_boxplot(position = position_dodge(width = 1), outlier.size = 0.7, width = 0.1, show.legend = FALSE, color = "black")+ 
  theme_bw(base_size = 16) + 
stat_compare_means(comparisons = my_comparisons, label = "p.signif", tip.length = 0) +
 facet_wrap(~variable, scales = "free", labeller = label_both) +  
  theme_minimal() +
  theme(panel.grid = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1), 
        axis.text.y = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(), 
        legend.key = element_blank()) +
  labs(x = '', y = '', title = 'BCRLJ_ratio in IGKC+Naïve B')+scale_fill_npg()
 P2A
 ggsave(plot = P2A,'Gao_TCRBCRchain_Figure/IGKCposNaïveBBCRLJ.pdf',width = 20,height = 40)
```
```{r}
library(dplyr)
library(purrr)
library(ggpubr)
library(ggsci)
# Subset the data
data_subset <- subset(BCRLJ2, CellType == "IGKC-Naïve B")
my_comparisons <- list(
  c("Early_PBMC", "Late_PBMC"),
  c("Early_PBMC", "Early_Liver"),
  c("Early_PBMC", "Early_Spleen"),
  c("Early_PBMC", "Early_Thymus"),
  c("Late_PBMC", "Early_Liver"),
  c("Late_PBMC", "Early_Spleen"),
  c("Late_PBMC", "Early_Thymus"),
  c("Early_Liver", "Early_Spleen"),
  c("Early_Liver", "Early_Thymus"),
  c("Early_Spleen", "Early_Thymus")
)
P8A=subset(BCRLJ2,CellType=="IGKC-Naïve B") %>% ggplot(aes(Organ_Stage,value,fill=Organ_Stage))+geom_boxplot(position = position_dodge(width = 1), outlier.size = 0.7, width = 0.1, show.legend = FALSE, color = "black")+ 
  theme_bw(base_size = 16) + 
stat_compare_means(comparisons = my_comparisons, label = "p.signif", tip.length = 0,method = "wilcox.test") +
 facet_wrap(~variable, scales = "free", labeller = label_both) +  
  theme_minimal() +
  theme(panel.grid = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1), 
        axis.text.y = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(), 
        legend.key = element_blank()) +
  labs(x = '', y = '', title = 'BCRLJ_ratio in IGKC-Naïve B')+scale_fill_npg()
 P8A
 ggsave(plot = P8A,'Gao_TCRBCRchain_Figure/IGKCnegNaïveBBCRLJ.pdf',width = 20,height = 40)
```

```{r}
my_comparisons <- list(
  c("Early_PBMC", "Late_PBMC")
 
)
P283=subset(BCRLJ2)%>% ggplot(aes(variable,value,fill=Organ_Stage))+geom_bar(stat = 'identity',position = "dodge")+ 
  # theme_bw(base_size = 16) + 
stat_compare_means(comparisons = my_comparisons, label = "p.signif", tip.length = 0) +
 facet_grid(CellType~variable, scales = "free", space='free', switch = "y") +
  theme_classic() +
  theme_bw(base_size = 16) +
  theme(panel.grid = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1), 
        axis.text.y = element_text(size = 12),
        plot.title = element_text(hjust = 0.5))+xlab("")+ylab("Composition (%)")+scale_fill_npg()
 P283
 
```

```{r}
# BCRLJ2$value %>% 
data_summary
```

```{r}
# library()
library(ggsci)
my_comparisons <- lapply(unique(data_summary$CellType), function(cell) {
  lapply(unique(data_summary$variable), function(var) {
    list(c(cell, var, "Early_PBMC", "Late_PBMC"))
  })
})
# First, calculate mean and se for each group
data_summary <- BCRLJ2 %>%
  group_by(CellType, variable, Organ_Stage) %>%
  summarise(mean_value = mean(value), se = sd(value) / sqrt(n()), .groups = 'drop')

# Define dodge width
dodge <- position_dodge(width = 0.9)
my_comparisons <- list(
  c("Early_PBMC", "Late_PBMC")
)

P284 <- ggplot(data_summary, aes(x = variable, y = mean_value, fill = Organ_Stage)) +
  geom_bar(stat = "identity", position = dodge) +
  geom_errorbar(aes(ymin = mean_value - se, ymax = mean_value + se), width = 0.6, position = dodge) +
  facet_grid(CellType ~ variable, scales = "free", space = 'free', switch = "y") +
  theme_classic() +
  theme_bw(base_size = 16) +
  theme(panel.grid = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(size = 14, angle = 45, hjust = 1), 
        axis.text.y = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        strip.text.x =  element_blank()) + # Remove facet labels
  xlab("") +
  ylab("Composition (%)") +
  scale_fill_npg() +
  stat_compare_means(comparisons = my_comparisons, method = "t.test", label = "p.signif",hide.ns = T)

print(P284)

P284
ggsave(plot=P284,"Gao_TCRBCRchain_Figure/BCRLJ_merge.pdf",width = 15,height = 10)
 # ggsave(plot = P8A,'Gao_TCRBCRchain_Figure/IGKCnegNaïveBBCRLJ.pdf',width = 20,height = 40)
```

```{r}
ggsave(plot=P284,"Gao_TCRBCRchain_Figure/BCRLJ_merge.pdf",width = 40,height = 10)
```

```{r}
# data_summary <- BCRLJ2 %>%
#   group_by(CellType, variable, Organ_Stage) %>%
#   summarise(median_value = median(value), ymin = quantile(value, 0.25), ymax = quantile(value, 0.75), .groups = 'drop')
# dodge <- position_dodge(width = 0.9)
# P284 <- ggplot(data_summary, aes(x = variable, y = median_value, fill = Organ_Stage)) +
#   geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
#   geom_errorbar(aes(ymin = ymin, ymax = ymax), width = 0.6, position = dodge) +
#   facet_grid(CellType ~ variable, scales = "free", space = 'free', switch = "y") +
#   theme_classic() +
#   theme_bw(base_size = 16) +
#   theme(panel.grid = element_blank(), 
#         panel.background = element_blank(), 
#         panel.border = element_blank(),
#         axis.line = element_line(color = "black"),
#         axis.text.x = element_text(size = 14, angle = 45, hjust = 1), 
#         axis.text.y = element_text(size = 12),
#         plot.title = element_text(hjust = 0.5),
#         strip.text.x =  element_blank()) + # Remove facet labels
#   xlab("") +
#   ylab("Composition (%)") +
#   scale_fill_npg() 
#   # stat_compare_means(comparisons = my_comparisons, method = "t.test", label = "p.signif", hide.ns = T)
# 
# print(P284)
```

