---
title: "Untitled"
output: html_document
date: "2024-08-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
load("../data/processed_data/M3.Rdata")
```

```{r}
plot_weights2 <- function(W, dot_size, text_size, color_manual = NULL, color_name = NULL, shape_name = NULL, scale = TRUE, abs = FALSE, legend = TRUE) {
  library(ggplot2)
  library(ggrepel)
  
  p <- ggplot(W, aes_string(x = "value", y = "feature_id", col = "labelling_group")) + 
    scale_y_discrete(expand = c(0.03, 0.03)) + 
    geom_point(aes_string(shape = "shape_by", size = "labelling_indicator")) + 
    labs(x = "Weight", y = "Rank", size = dot_size)
  
  if (nrow(W[W$labelling_group != "0", ]) > 0) {
    p <- p + geom_text_repel(
      data = W[W$labelling_group != "0", ], 
      aes_string(label = "feature", col = "labelling_group"), 
      size = text_size, segment.alpha = 0.25, segment.color = "black", 
      segment.size = 0.3, show.legend = FALSE, max.overlaps = Inf
    )
  }
  
  if (scale) {
    if (abs) {
      p <- p + coord_cartesian(xlim = c(0, 1)) + 
        scale_x_continuous(breaks = c(0, 1)) + 
        expand_limits(x = c(0, 1))
    } else {
      p <- p + coord_cartesian(xlim = c(-1, 1)) + 
        scale_x_continuous(breaks = c(-1, 0, 1)) + 
        expand_limits(x = c(-1, 1))
    }
  }
  
  p <- p + scale_size_manual(values = c(dot_size/2, dot_size * 2)) + 
    guides(size = "none")
  
  if (!is.null(color_name)) {
    p <- p + labs(color = color_name)
  } else {
    foo <- c("grey", "black", color_manual)
    names(foo) <- as.character(0:(length(foo) - 1))
    p <- p + guides(color = "none") + scale_color_manual(values = foo)
  }
  
  if (!is.null(shape_name)) {
    p <- p + labs(shape = shape_name)
  } else {
    p <- p + guides(shape = "none")
  }
  
  if (length(unique(W$factor)) > 1) {
    p <- p + facet_wrap(~factor, nrow = 1, scales = "free")
  }
  
  p <- p + theme_bw() + 
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5), 
      axis.title = element_text(size = rel(1.3), color = "black"), 
      axis.text.x = element_text(size = rel(1.3), color = "black"), 
      axis.text.y = element_blank(), 
      axis.ticks.y = element_blank(), 
      strip.text = element_text(size = rel(1.2)), 
      panel.spacing = unit(1, "lines"), 
      panel.grid.major.y = element_blank()
    )
  
  if (legend) {
    p <- p + theme(
      legend.text = element_text(size = rel(1.2)), 
      legend.title = element_text(size = rel(1.2))
    )
  } else {
    p <- p + theme(legend.position = "none")
  }
  
  return(p)
}
```

```{r}
DataCell
```
```{r}
DataCell2<-subset(DataCell,Oldview!="CD56highCD16low_NK")
rownames(DataCell2)<-DataCell2$View
sorted_values2 <- c(
  "HSC_MPP",     
  "MEMP",           
  "MEP",           

  "Na誰ve CD4 T","Treg", "Na誰ve CD8 T", 
   "Gamma Delta V2 T", 
  "Th17like_INNATE_T", 
  "NK T",  "CX3CR1+ NK", "CXCR6+ NK",  
  "CXCR5- Na誰ve B", "CXCR5+ Na誰ve B",   "Myeloid-CD177",  
  "CD14+PPBP+ Monocytes", "Classical Monocytes", 
  "DC2", "pDC",      
  "Cell_stimulate_BulkRNA", "Cell_stimulate_Olink", 
  "Plama_Olink", "Sflow_Freq_inParent","CD4TCR", "CD8TCR",  "BCR"
)
DataCell2<-DataCell2[sorted_values2,]
```

```{r}
library(MOFA2)
for (i in 1:nrow(DataCell2)) {
  Viewname=DataCell2$Oldview[i]
  Pw1=plot_weights(mofa, factor=3, view=, nfeatures=10,return_data = T)
  Pw1
  name=DataCell2$View[i]
  Pw1$feature<- sub(".*__", "", Pw1$feature)
  plot_weights2(Pw1,dot_size = 0.5,text_size = 3)+ggtitle(name)
}

```
```{r}
DataCell2
```

```{r}
library(MOFA2)
library(ggplot2)
library(patchwork)

plot_list <- list()

for (i in 1:nrow(DataCell2)) {
  Viewname <- DataCell2$Oldview[i]
  Pw1 <- plot_weights(mofa, factor=3, view=Viewname, nfeatures=10, return_data = TRUE)
  
  name <- DataCell2$View[i]
  Pw1$feature <- sub(".*__", "", Pw1$feature)
  
   Pw1$feature <- gsub("_Plama_Olink", "", Pw1$feature)
    Pw1$feature <- gsub("_Cell_stimulate_Olink", "", Pw1$feature)
   Pw1$feature <- gsub("_CD4TCR", "", Pw1$feature)
   Pw1$feature <- gsub("_CD8TCR", "", Pw1$feature)
  Pw1$feature=gsub("CXCR5.B.1" ,"CXCR5+ B" ,Pw1$feature) %>%
gsub("CXCR5.B" ,"CXCR5- B" ,.)%>% gsub("Inhibitory.CD8.T" ,"Inhibitory CD8+T" ,.)%>% gsub("_CD4TCR" ,"" ,.)%>% gsub("_CD8TCR" ,"" ,.)
  p <- plot_weights2(Pw1, dot_size = 0.5, text_size = 3) + ggtitle(name)
  plot_list[[i]] <- p
}


combined_plot2 <- wrap_plots(plot_list, ncol = 5)


# print(combined_plot)

dev.off()
ggsave("../output/plots/combined_weights_plot.pdf", combined_plot2, width = 20, height = 20, limitsize = FALSE)
```

```{r}
library(dplyr)

clean_feature_names <- function(feature) {
  feature %>%
    sub(".*__", "", .) %>%
    gsub("_Plama_Olink", "", .) %>%
    gsub("_Cell_stimulate_Olink", "", .) %>%
    gsub("_CD4TCR", "", .) %>%
    gsub("_CD8TCR", "", .) %>%
    gsub("CXCR5.B.1", "CXCR5+ B", .) %>%
    gsub("CXCR5.B", "CXCR5- B", .) %>%
    gsub("Inhibitory.CD8.T", "Inhibitory CD8+T", .) %>%
    gsub("_CD4TCR", "", .) %>%
    gsub("_CD8TCR", "", .)
}
```

```{r}
library(ggplot2)

plot_custom_weights <- function(mofa, view, factors, nfeatures, title = "BCR", fill_color = "grey") {

  negative_weights <- plot_top_weights(mofa, view = view, factors = factors, sign = "negative", nfeatures = nfeatures)
  negative_weights_data <- negative_weights$data
  negative_weights_data$feature=clean_feature_names(negative_weights_data$feature)
  negative_weights_data$value <- -negative_weights_data$value

  positive_weights <- plot_top_weights(mofa, view = view, factors = factors, sign = "positive", nfeatures = nfeatures)
  positive_weights_data <- positive_weights$data
  positive_weights_data$feature=clean_feature_names(positive_weights_data$feature)

  combined_weights_data <- rbind(negative_weights_data, positive_weights_data)

  ggplot(combined_weights_data, aes(x = reorder(feature, value), y = value)) +
    geom_bar(stat = "identity", fill = fill_color) +
    geom_text(aes(x = reorder(feature, value), y = ifelse(value > 0, -0.01, 0.01), label = feature), 
              angle = 90, hjust = ifelse(combined_weights_data$value > 0, 1, 0), vjust = 0.5) +
    scale_y_continuous(limits = c(-1, 1), breaks = seq(-1, 1, by = 0.5)) +
    labs(x = "", y = "", title = title) +
    theme_classic() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank(),
      axis.line.x = element_blank(),
      plot.title = element_text(hjust = 0.5)  
    )
}


plot_custom_weights(mofa, view = "BCR", factors = 3, nfeatures = 6, title = "Custom BCR Title", fill_color = "blue")
```

```{r}
library(ggplot2)
library(patchwork)
mop_cells_palette = c(
    '#E41A1C',  
    '#FF7F00',  
    '#FFD92F', 
    '#E6AB02',  
    '#FFFF99',  
    '#BC80BD', 
    '#1B9E77', 
    '#66C2A5',  
    '#8DA0CB',  
    '#A6CEE3',  
    '#B3E2CD', 
    '#FFFFB3', 
    '#FB8072',  
    '#80B1D3',  
    '#FDB462',  
    '#B3DE69',  
    '#FCCDE5',  
    '#D9D9D9', 
    '#BC80BD',
    '#CCEBC5',  
    '#377EB8',"#11A579","#F2B701","#66C5CC","#80BA5A","#F6CF71" 
)
output_dir <- "../output/plots/MOFA/np_weight/"

dir.create(output_dir, showWarnings = FALSE)

Aplot_list <- list()
n=0
for (i in 1:nrow(DataCell2)) {
  n=n+1
 Viewname <- DataCell2$Oldview[i]
  # Pw1 <- plot_weights(mofa, factor=3, view=Viewname, nfeatures=10, return_data = TRUE)
  
  name <- DataCell2$View[i]
  o1 <- plot_custom_weights(mofa, view = Viewname, factors = 3, nfeatures = 6, title = i, fill_color = rev(mop_cells_palette)[n])+ggtitle(name)

  ggsave(plot = o1, filename = paste0(output_dir, "/", Viewname, ".pdf"), width = 6, height = 4)

  Aplot_list[[i]] <- o1
}

Acombined_plot <- wrap_plots(Aplot_list)

ggsave(plot = Acombined_plot, filename = paste0(output_dir, "/Acombined_plot.pdf"), width = 20, height = 18)
```
```{r}
save.image("../data/processed_data/M4.Rdata")
```

