---
title: "Untitled"
output: html_document
date: "2023-11-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```
```{r}
system("mkdir -p /home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24")
system("mkdir -p /home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S23")
system("mkdir -p /home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24")
```


```{r}
library(data.table)
library(tidyverse)
```

```{r}
BCRobs=read.csv("/data5/maolp/Gaofeng_All_matrix/Allcount//All_scanpyData/Data/BCRobs.csv")
BCRobs
```
```{r}
TCRobs=read.csv("/data5/maolp/Gaofeng_All_matrix/Allcount//All_scanpyData/Data/TCRobs.csv")
TCRobs

```

```{r}
TCRobs<-TCRobs[grep("PBMC",TCRobs$New_Body),]
TCRobs<-subset(TCRobs,Last_cell_type=="Naïve CD4 T")
# TRB=fread("IMGT_HTRBV-QUEST/TRB/mydir_6_Junction.txt",header = T) %>% as.data.frame()
```

```{r}

read_and_assign <- function(folder) {
  file_path <- paste0("IMGT_HighV-QUEST/",folder, "/6_Junction.txt")
  # print(file_path)
  assign(paste0(folder, "_data"), fread( file_path ,header = T), envir = .GlobalEnv)
}


folders <- c( "TRA", "TRB")


lapply(folders, read_and_assign)
```
```{r}
# colnames(TRB_data)
# TRB_data$`V-DOMAIN ID`<-
TRB_data
```

```{r}
TCRobs$VID<-paste0(TCRobs$Cellname,"_B")
TRB_data2<-merge(TRB_data,TCRobs,by.x="Sequence ID",by.y="Cellname")
TRB_data2$ntlen=nchar(TRB_data2$JUNCTION)
TRB_data2$Week<-substring(TRB_data2$AdjustedID,2,5) %>% as.numeric()
TRB_ntlen=TRB_data2[,c("Week","ntlen","AdjustedID")]
TRBnttable=table(TRB_ntlen$AdjustedID,TRB_ntlen$ntlen) %>% as.data.frame()
colnames(TRBnttable)<-c("AdjustedID","Ntlen","Freq")
TRBnttable2=TRBnttable %>%
  group_by(AdjustedID,Ntlen) %>%
  summarise(Freq_sum = sum(Freq)) %>%
  mutate(Freq_ratio = Freq_sum / sum(Freq_sum)) %>% mutate(Week=as.numeric(substring(AdjustedID,2,5)))%>%mutate(Ntlen=as.character(Ntlen))
```

```{r}
ggplot(TRBnttable2)+geom_point(aes(as.numeric(Ntlen),Freq_ratio,color=Week))+geom_smooth(aes(as.numeric(Ntlen),Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()
```
```{r}
process_TRB_data <- function(TRB_data, junction_field) {
  data <- TRB_data
  data$ntlen <- nchar(data[[junction_field]])

  data_sub <- data[, c( "ntlen", "AdjustedID")]
  nt_table <- table(data_sub$AdjustedID, data_sub$ntlen) %>% as.data.frame()
  print("test")
  colnames(nt_table) <- c("AdjustedID", "Ntlen", "Freq")
  print("test2")
  nt_table2 <- nt_table %>%
    group_by(AdjustedID, Ntlen) %>%
    summarise(Freq_sum = sum(Freq)) %>%
    mutate(Freq_ratio = Freq_sum / sum(Freq_sum)*100) %>%
    mutate(Week = as.numeric(substring(AdjustedID, 2, 5))) %>%
    mutate(Ntlen =as.numeric( as.character(Ntlen)))
  
  return(nt_table2)
}


process_TRB_data(TRB_data2, "3'V-REGION") %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()
```

```{r}
process_TRB_data(TRB_data2, "5'J-REGION") %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()
```

```{r}
TRB_ntlen1=TRB_data2
TRB_ntlen1$ntlen <- nchar(TRB_ntlen1[["N2-REGION"]])
TRB_ntlen=TRB_ntlen1[,c("Week","ntlen","AdjustedID")]
TRBnttable=table(TRB_ntlen$AdjustedID,TRB_ntlen$ntlen) %>% as.data.frame()
colnames(TRBnttable)<-c("AdjustedID","Ntlen","Freq")
TRBnttable2=TRBnttable %>%
  group_by(AdjustedID,Ntlen) %>%
  summarise(Freq_sum = sum(Freq)) %>%
  mutate(Freq_ratio = Freq_sum / sum(Freq_sum)) %>% mutate(Week=as.numeric(substring(AdjustedID,2,5)))%>%mutate(Ntlen=as.character(Ntlen))
# TRBnttable2 %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()+ggtitle(CDRlocus)
TRB_data2[,c( "ntlen", "AdjustedID")]
```

```{r}
CDRlocus="N-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()+ggtitle(CDRlocus)
# TRB_data2[,c( "ntlen", "AdjustedID")]
```

```{r}
CDRlocus="N1-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()+ggtitle(CDRlocus)
```

```{r}
CDRlocus="N-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_c()+theme_classic()+ggtitle(CDRlocus)
```


```{r}
CDRlocus="N2-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_c()+theme_classic()+ggtitle(CDRlocus)
```
```{r}
CDRlocus="3'V-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_c()+theme_classic()+ggtitle(CDRlocus)
```

```{r}
CDRlocus="5'J-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_c()+theme_classic()+ggtitle(CDRlocus)
```
```{r}
CDRlocus="D-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_c()+theme_classic()+ggtitle(CDRlocus)
```
```{r}
process_TRB_data(TRB_data2, "5'J-REGION") %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()
```

```{r}
Celltype="CD8 TRB"
```


```{r}
CDRlocus="N2-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype,"_",CDRlocus,".pdf"),width = 6,height =4)
```
```{r}
CDRlocus="3'V-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
```

```{r}
CDRlocus="5'J-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
```

```{r}
CDRlocus="D-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
```


```{r}


process_TRB_data2 <- function(TRB_data, junction_field) {
  data <- TRB_data
  data$ntlen <- nchar(data[[junction_field]])

  data_sub <- data[, c( "ntlen", "AdjustedID")]
  nt_table <- table(data_sub$AdjustedID, data_sub$ntlen) %>% as.data.frame()
  # print("test")
  colnames(nt_table) <- c("AdjustedID", "Ntlen", "Freq")
  # print("test2")
  nt_table2 <- nt_table %>%
    group_by(AdjustedID, Ntlen) %>%
    summarise(Freq_sum = sum(Freq)) %>%
    mutate(Freq_ratio = Freq_sum / sum(Freq_sum)*100) %>%
    mutate(Week = as.numeric(substring(AdjustedID, 2, 5))) %>%
    mutate(Ntlen =as.numeric( as.character(Ntlen)))
  nt_table2$Alen=paste0(junction_field,"_",nt_table2$Ntlen)
  return(nt_table2)
}
CDRlocus="D-REGION"

DREGION=process_TRB_data2(TRB_data2,CDRlocus )

Dall=data.frame()
for (i in c("N1-REGION","N2-REGION","5'J-REGION","3'V-REGION","D-REGION")) {
  tem=process_TRB_data2(TRB_data2,i )
  Dall=rbind(Dall,tem)
}
```

```{r}
head(Dall)
Dall2=Dall[,c("AdjustedID","Alen","Freq_ratio")]

Dall2_wide <- Dall2 %>% 
  pivot_wider(names_from = Alen, values_from = Freq_ratio)

Dall2_wide <- spread(Dall2, Alen, Freq_ratio) %>% as.data.frame()
rownames(Dall2_wide)<-Dall2_wide$AdjustedID
Dall2_wide<-Dall2_wide[,-1]
```

```{r}
source("~/Main_Gao_ScanpyProject20231130/HFB_script_in_save/Mainrun.R")
```


```{r}
library(factoextra)
Dall2_pca <- prcomp(Dall2_wide)

fviz_pca_ind(Dall2_pca  , repel=T)
```

```{r}

groups=c(rep("Early PBMC",11),rep("Late PBMC",10))
P1=fviz_pca_ind(Dall2_pca,
             col.ind = groups, # color by groups
             palette =c('#7570b3','red'),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "confidence",
             legend.title = "Groups",title='TCR TRB CDR3 5V+N1+D+N2+5J Percentage length(nt) PCA',
             repel = TRUE,ggtheme = theme_classic()
             )+theme(aspect.ratio = 1)
P1
```
```{r}
TRBmain=P1$data
TRBmain$Week<-substring(TRBmain$name,2,5) %>% as.numeric()
TRBmain$Week=TRBmain$Week-2
ggplot(TRBmain)+geom_point(aes(x,y=y,color=Week),size=3)+theme_classic()+scale_colour_viridis_c()+xlab("Dim1(92.6%)")+ylab("Dim2(3.1%)")+theme(aspect.ratio = 1)
```



```{r}
CDRlocus="N-REGION"
process_TRB_data(TRB_data2,CDRlocus ) %>% ggplot()+geom_point(aes(Ntlen,Freq_ratio,color=Week))+geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F)+scale_color_viridis_b()+theme_classic()+ggtitle(CDRlocus)
```

```{r}
CDRlocus="N1-REGION"
PN1=process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
PN1
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
```


```{r}
Dfcalculate_correlation(process_TRB_data(TRB_data2,CDRlocus ), "Ntlen", "Week", "Freq_ratio") %>% create_pval_plot(.,titlex=CDRlocus)+xlab("lengths(nt)")
```
```{r}

```


```{r}
  TRA_data2fun<-function(data, junction_field) {
  data <- data
  data$ntlen <- nchar(data[[junction_field]])

  data_sub <- data[, c( "ntlen", "AdjustedID")]
  return(data_sub)}
TRA_data2fun(TRB_data2,CDRlocus )  %>% 
  ggplot()+geom_density(aes(ntlen,fill=AdjustedID))+theme_classic()
```

```{r}

```

```{r}
CDRlocus="N2-REGION"
PN2=process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)

```

```{r}
  TRA_data2fun<-function(data, junction_field) {
  data <- data
  data$ntlen <- nchar(data[[junction_field]])

  data_sub <- data[, c( "ntlen", "AdjustedID")]
  return(data_sub)}
TRA_data2fun(TRB_data2,CDRlocus )  %>% 
  ggplot()+geom_density(aes(ntlen,fill=AdjustedID))+theme_classic()
```

```{r}
CDRlocus="3'V-REGION"
P3V=process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
```

```{r}
CDRlocus="5'J-REGION"
P5J=process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
```

```{r}
CDRlocus="D-REGION"
PD=process_TRB_data(TRB_data2,CDRlocus ) %>% 
  ggplot()+
  geom_point(aes(Ntlen,Freq_ratio,color=Week),shape=1)+
  geom_smooth(aes(Ntlen,Freq_ratio,group=Week,color=Week),se=F,size=0.3)+
  scale_color_viridis_c(breaks = c(10, 20,  30, 39))+
  theme_classic()+
  ggtitle(paste0("All TRB  ",CDRlocus))+
  theme_linedraw() +
  xlab('Length(nt)') +
  ylab('ratio(%)') +
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
       panel.border = element_rect(linetype = "solid", colour = "black", size = 1.5))+
  labs(color="pcw")+  scale_color_gradientn(colours = rev(colorRampPalette(c("#C71000B2","#FF6F00B2","#6a73cf","#00AF99" ))(100)))
ggsave(paste0("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24/",Celltype," ",CDRlocus,".pdf"),width = 6,height =4)
Dfcalculate_correlation(process_TRB_data(TRB_data2,CDRlocus ), "Ntlen", "Week", "Freq_ratio") %>% create_pval_plot(.,titlex=CDRlocus)+xlab("lengths(nt)")
```
```{r}
CDRlocus="D-REGION"
process_TRB_data(TRB_data2,CDRlocus )
```
```{r}
library(ggplot2)
library(gridExtra)


Pall=grid.arrange(P3V,PN1, PD,PN2,P5J, ncol = 1)

ggsave(plot=Pall,"/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24//AllTRB.pdf", width = 6, height = 20, dpi = 300)

```
```{r}

```


```{r}
plt_list=list()
for (i in c("N1-REGION","N2-REGION","3'V-REGION","5'J-REGION","D-REGION")) {
  print(i)
  px=Dfcalculate_correlation(process_TRB_data(TRB_data2,i ), "Ntlen", "Week", "Freq_ratio") %>% create_pval_plot(.,titlex=i)+xlab("lengths(nt)")
  plt_list[[i]]=px
}

plt_list[[5]]
library(gridExtra)


Psig=grid.arrange(
  plt_list[["N1-REGION"]],
  plt_list[["N2-REGION"]],
  plt_list[["3'V-REGION"]],
  plt_list[["5'J-REGION"]],
  plt_list[["D-REGION"]],ncol = 1
)
system("mkdir -p /home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24sig")
ggsave(plot=Psig,"/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24sig/CD8TRBsig.pdf", width = 6, height = 16, dpi = 600)
```

```{r}
Immusig_plot(TRB_data2, c("N1-REGION", "N2-REGION", "3'V-REGION", "5'J-REGION", "D-REGION"), "TRB",
                         "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure4/S24sig/CD8TRBsig.pdf")
```

