---
title: "Untitled"
output: html_document
date: "2023-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#-------------------------------
### 加载R包


```{r}
rm(list=ls())
```

```{r}
library(CellChat)
library(tidyverse)
source("Figure3_step3_organall_load.R")
```



#-------------------------------
### 细胞类型

```{r}
source("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_script_in_save/Cell_types_list-copy.R")
```

### 前面数据
```{r}
Organresults=readRDS( "/home/maolp/Allcount/All_scanpyData/Cellchat/Organ_results_rmcl2.rds")
```


```{r}

```

```{r}
GroupStat_ids <- c( "PBMC_Early","PBMC_Late" ,"Liver_Early","Thymus_Early", "Spleen_Early")
Organ_cellchat2 <- mergeCellChat(Organresults, add.names =GroupStat_ids)
```
```{r}
setdiff(Cell_types_list3,unique(Organ_cellchat2@meta$labels))
setdiff(unique(Organ_cellchat2@meta$labels),cell_types_list)
```
### 查看和4.2有无区别
```{r}
gg1 <- compareInteractions(Organ_cellchat2 , show.legend = F, group = c(1,2,3,4,5))+scale_fill_manual(values = c("#FFA300","#F6313E", "#fb862b", "#0eb0c8", "#6a73cf"))
gg2 <- compareInteractions(Organ_cellchat2 , show.legend = F, group = c(1,2,3,4,5), measure = "weight")+scale_fill_manual(values = c("#FFA300","#F6313E", "#fb862b", "#0eb0c8", "#6a73cf"))
gg1 + gg2
```


### 初步处理
```{r}

object.list=Organresults
object.list <- lapply(object.list, function(x) netAnalysis_computeCentrality(x, slot.name = "netP"))
```
### 加载颜色
```{r}
# %%R -w 3000 -h 1200 -r 180
library(ggsci)
cols01 <- c("#f49128", "#194a55", "#187c65", "#f26115", "#c29f62", "#83ba9e")
cols02 <- c("#c62d17", "#023f75", "#ea894e", "#266b69", "#eb4601", "#f6c619")
cols03 <- c("#fa6e01", "#2f2f2f", "#972b1d", "#e6a84b", "#4c211b", "#ff717f")
cols04 <- c("#223e9c", "#b12b23", "#aebea6", "#edae11", "#0f6657", "#c74732")
cols05 <- c("#6a73cf", "#edd064", "#0eb0c8", "#f2ccac", "#a1d5b9", "#e1abbc")

all_colors <- c(cols01, cols02, cols03, cols04, cols05)
all_colors
colorname2=c(pal_futurama()(3),"#46A040","#00AF99" ,"#F6313E", "#FFA300","#2f2f2f",  "#FFC179", 
"#FF5A00", "#663366","#FF6666","#8F1336", "#0081C9", "#001588", "#CC0033",
"#CC9966","#CC0033","#999933","#009966","#CCCC33","#CCFF99","#0eb0c8","#993333","#333366",
"#490C65", "#BA7FD0","#A6CEE3", "#1F78B4", "#DE77AE", "#B2DF8A", "#006D2C", "#B5AD64",
"#9DA8E2","#91C392", "#194a55", "#187c65", "#c29f62","#f49128","#c62d17", "#333329",
"#023f75", "#ea894e", "#266b69",  "#e1abbc","#f6c619","#fa6e01", "#972b1d", "#e6a84b", "#4c211b", "#ff717f","#223e9c", 
"#aebea6", "#edae11", "#c74732", "#6a73cf", "#edd064" , 
"#0eb0c8", "#f2ccac" ,"#868686","#339966", "#83ba9e", "#b12b23", "#0f6657","#f26115","#eb4601")
colorname3=colorname2
length(colorname3)
```

```{r}
# %%R -w 1800 -h 2600 -r 180

library(jsonlite)


file_path <- "/home/maolp/Allcount/Last_All_scanpyData/ColorDict/Celltype_colors_dict_nonum.json"
colors_dict <- fromJSON(file_path)
# colors_dict
```






```{r}
# levels(P1$data$source.target)
# 
# Spleen_Earlyname <- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$Spleen_Early$prob))] 
# 
# paste0(Spleen_Earlyname ," -> abTentry (Spleen_Early)")
# setdiff(levels(P1$data$source.target),paste0(Spleen_Earlyname ," -> abTentry (Spleen_Early)"))
# setdiff(levels(P1$data$source.target),paste0(Spleen_Earlyname ," -> abTentry (Spleen_Early)"))
```


```{r}
# P1$data$source.target<-factor(P1$data$source.target,levels = paste0(Spleen_Earlyname ," -> abTentry (Spleen_Early)"))
# pplot(P1$data,vjust.x=1,hjust.x=01,angle.x=45)+ geom_vline(xintercept = seq(1.5, 31 - 0.5, 1), lwd = 0.1, colour = "grey")

```

```{r}

# setdiff(cell_types_list,levels(Organ_cellchat2@idents$Thymus_Early))
```

```{r}
setdiff(cell_types_list,levels(Organ_cellchat2@idents$Thymus_Early))
Organ_cellchat2@idents$Thymus_Early<-factor(Organ_cellchat2@idents$Thymus_Early,levels = cell_types_list[-29])

# setdiff(cell_types_list,levels(Organ_cellchat2@idents$Thymus_Early))
```
### 相关细胞类型
```{r}
cell_types_list=Cell_types_list3
```


```{r}
PBMC_Earlyname <- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$PBMC_Early$prob))]
PBMC_latename <- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$PBMC_Late$prob))]

Liver_earlyname<- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$Liver_Early$prob))]
Spleen_Earlyname<- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$Spleen_Early$prob))]

Spleen_Earlyname<- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$Spleen_Early$prob))]

Thymus_Earlyname<- cell_types_list[!cell_types_list %in% setdiff(cell_types_list,colnames(Organ_cellchat2@net$Thymus_Early$prob))]
```




```{r}
PBMC_Earlyname
```

```{r}
PBMC_latename
```

```{r}
Liver_earlyname
```

```{r}
Spleen_Earlyname
```

```{r}
Thymus_Earlyname
```

### 重新赋值idents

```{r}
Organ_cellchat2@idents$PBMC_Early<-factor(Organ_cellchat2@idents$PBMC_Early,levels = PBMC_Earlyname)

Organ_cellchat2@idents$PBMC_Late<-factor(Organ_cellchat2@idents$PBMC_Late,levels =PBMC_latename)
Organ_cellchat2@idents$Liver_Early<-factor(Organ_cellchat2@idents$Liver_Early,levels =Liver_earlyname)

Organ_cellchat2@idents$Thymus_Early<-factor(Organ_cellchat2@idents$Liver_Early,levels =Thymus_Earlyname)
Organ_cellchat2@idents$Spleen_Early<-factor(Organ_cellchat2@idents$Spleen_Early,levels =Spleen_Earlyname)
```

```{r}
seqcolor4_bwr=c("#2166ac","#518bbd","#F0E68C","#d25e55","#b2182b")
custom_cmap2 <- colorRampPalette(c(seqcolor4_bwr))(100)
```


### Naive CD8 end

```{r}
CD8_PBMC_early <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use =grep("CD8 T",PBMC_Earlyname),  comparison = c(1), angle.x = 45,color.text = colorname2[8])+labs(title = "PBMC_early")+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S16/CD8_PBMC_early.pdf", plot = CD8_PBMC_early,width = 10,height = 6)

CD8_PBMC_late <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("CD8 T",PBMC_latename),  comparison = c(2), angle.x = 45,color.text = colorname2[8])+labs(title = "PBMC_late")+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S16/CD8_PBMC_late.pdf", plot = CD8_PBMC_late,width = 10,height = 6)

CD8_PBMC_early_late <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:30) , targets.use =grep("CD8 T",PBMC_latename),  comparison = c(1,2), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S16/CD8_PBMC_early_late.pdf", plot = CD8_PBMC_early_late,width = 20,height = 6)

Liver_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("CD8 T",Liver_earlyname),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S16/Liver_CD8_T.pdf", plot = Liver_CD8_T,width = 10,height = 6)
```


```{r}
Thymus_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("CD8 T",Thymus_Earlyname),  comparison = c(4), angle.x = 45,color.text = colorname2[8])
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S16/Thymus_CD8_T.pdf", plot = Thymus_CD8_T)

Spleen_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = c(12),  comparison = c(5), angle.x = 45,color.text = colorname2[8])
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S16/Spleen_CD8_T.pdf", plot = Spleen_CD8_T)

# PBMC_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",PBMC_Earlyname) , targets.use =c(1:31),  comparison = c(1), angle.x = 45,color.text = colorname2[8])
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_Early_CD8_T.pdf", plot = PBMC_Early_CD8_T)
```

```{r}
# netVisual_bubble

```
```{r}
# as.character(unique(PNK$data$interaction_name))[grepl("CD8",as.character(unique(PNK$data$interaction_name)))]
```

```{r}

CellChat_PBMC2 <- Organ_cellchat2


# CellChat_PBMC2@interactions <- CellChat_PBMC2@interactions[-which(CellChat_PBMC@interactions$interaction_name %in% as.character(unique(PNK$data$interaction_name))[grepl("CD8",as.character(unique(PNK$data$interaction_name)))]),]


# netVisual_bubble(CellChat_object, ...)
```
```{r}
# PNK$data
```

```{r}

```

```{r}
library(CellChat)
PNK2=netVisual_bubble(Organ_cellchat2, sources.use =c(1:3), targets.use =grep(" NK",PBMC_Earlyname) , comparison = c(1,2), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
PNK2

# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_Early_2CD8_T_comparison.pdf", plot = PBMC_Early_CD8_T_comparison,width = 14,height = 6)
# PNK
```

```{r}
# ggsave(plot=PNK,"/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PNKend.pdf",width = 24,height = 6)
```

```{r}
PBMC_Early_CD8_T_comparison <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:30), targets.use =grep("CD8 T",PBMC_Earlyname) ,  comparison = c(1,2), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_Early_2CD8_T_comparison.pdf", plot = PBMC_Early_CD8_T_comparison,width = 14,height = 6)

Liver_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = grep("CD8 T",Liver_earlyname),  comparison = c(3), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Liver_Early_2CD8_T.pdf", plot = Liver_Early_CD8_T,width = 10,height = 6)
```


```{r}
Thymus_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =  c(1:33), targets.use =grep("CD8 T",Thymus_Earlyname),  comparison = c(4), angle.x = 45,color.text = colorname2[c(8)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Thymus_Early_2CD8_T.pdf", plot = Thymus_Early_CD8_T,width = 10,height = 6)
```

```{r}
Spleen_Early_2CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use =  c(1:33), targets.use =grep("CD8 T",Spleen_Earlyname),  comparison = c(5), angle.x = 45,color.text = colorname2[c(8)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Spleen_Early_2CD8_T.pdf", plot = Spleen_Early_2CD8_T,width = 10,height = 6)
```
                                                                                           
```{r}
PBMC_early <- netVisual_bubble(Organ_cellchat2, sources.use = c(1:31), targets.use = c(11), comparison = c(1), angle.x = 45, color.text = colorname2[8]) + labs(title = "PBMC_early")+ scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_early.pdf", plot = PBMC_early)

PBMC_late <- netVisual_bubble(Organ_cellchat2, sources.use = c(1:31), targets.use = c(11), comparison = c(2), angle.x = 45, color.text = colorname2[8]) + labs(title = "PBMC_late")+ scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_late.pdf", plot = PBMC_late)

PBMC_early_late <- netVisual_bubble(Organ_cellchat2, sources.use = c(1:30), targets.use = c(11), comparison = c(1,2), angle.x = 45, color.text = colorname2[c(8,13)])+ scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_early_late.pdf", plot = PBMC_early_late)

Liver_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = c(1:31), targets.use = grep("CD8 T",Liver_earlyname), comparison = c(3), angle.x = 45, color.text = colorname2[8])+ scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Liver_CD8_T.pdf", plot = Liver_CD8_T)
```


```{r}
Thymus_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = c(1:31), targets.use = grep("CD8 T",Thymus_Earlyname), comparison = c(4), angle.x = 45, color.text = colorname2[8])+ scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Thymus_CD8_T.pdf", plot = Thymus_CD8_T)

Spleen_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = c(1:33), targets.use = c(12), comparison = c(5), angle.x = 45, color.text = colorname2[8])+ scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Spleen_CD8_T.pdf", plot = Spleen_CD8_T)

PBMC_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = grep("CD8 T",PBMC_Earlyname), targets.use = c(1:31), comparison = c(1), angle.x = 45, color.text = colorname2[8])+ scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_Early_CD8_T.pdf", plot = PBMC_Early_CD8_T)
```

### Naive CD8 source

```{r}
PBMC_Early_CD8_T_comparison <- netVisual_bubble(Organ_cellchat2, sources.use = grep("CD8 T",PBMC_Earlyname), targets.use = c(1:30), comparison = c(1,2), angle.x = 45, color.text = colorname2[c(8,13)]) + scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/PBMC_Early_CD8_T_comparison.pdf", plot = PBMC_Early_CD8_T_comparison,width = 15,height = 6)
```


```{r}
Liver_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = grep("CD8 T",Liver_earlyname), targets.use = c(1:33), comparison = c(3), angle.x = 45, color.text = colorname2[c(8,13)]) + scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Liver_Early_CD8_T.pdf", plot = Liver_Early_CD8_T,width = 10,height = 6)
```


```{r}
Thymus_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = grep("CD8 T",Thymus_Earlyname), targets.use = c(1:33), comparison = c(4), angle.x = 45, color.text = colorname2[c(8,13)]) + scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Thymus_Early_CD8_T.pdf",width = 10,height = 7)
```
```{r}
Spleen_Early_CD8_T <- netVisual_bubble(Organ_cellchat2, sources.use = grep("CD8 T",Spleen_Earlyname), targets.use = c(1:33), comparison = c(5), angle.x = 45, color.text = colorname2[c(8,13)]) + scale_color_gradientn(colours = custom_cmap2)
ggsave(plot = Spleen_Early_CD8_T ,filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Spleen_Early_CD8_T.pdf",width = 10,height = 7)
```





#### PBMC_early

```{r}
Ptest1=  netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = c(11),  comparison = c(1), angle.x = 45,color.text = colorname2[8])+labs(title = "PBMC_early")
Ptest1$data
```

```{r}
  netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = c(11),  comparison = c(1), angle.x = 45,color.text = colorname2[8])+labs(title = "PBMC_early")+scale_color_gradientn(colours = custom_cmap2)
```

#### PBMC_late
```{r}
  netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = c(11),  comparison = c(2), angle.x = 45,color.text = colorname2[8])+labs(title = "PBMC_late")+scale_color_gradientn(colours = custom_cmap2)
```
```{r}
  netVisual_bubble(Organ_cellchat2, sources.use =c(1:30) , targets.use = c(11),  comparison = c(1,2), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
```
```{r}
# "#FF6F00FF" "#C71000FF" "#008EA0FF" "#46A040"   "#00AF99"   "#F6313E"   "#FFA300"   "#2f2f2f"  
#  [9] "#FFC179"   "#FF5A00"   "#663366"   "#FF6666"   "#8F1336"   "#0081C9"   "#001588"   "#CC0033"  
# [17] "#CC9966"   "#CC0033"   "#999933"   "#009966"   "#CCCC33"   "#CCFF99"   "#0eb0c8"   "#993333"  
# [25] "#333366"   "#490C65"   "#BA7FD0"   "#A6CEE3"   "#1F78B4"   "#DE77AE"   "#B2DF8A"   "#006D2C"  
# [33] "#B5AD64"   "#9DA8E2"   "#91C392"   "#194a55"   "#187c65"   "#c29f62"   "#f49128"   "#c62d17"  
# [41] "#333329"   "#023f75"   "#ea894e"   "#266b69"   "#e1abbc"   "#f6c619"   "#fa6e01"   "#972b1d"  
# [49] "#e6a84b"   "#4c211b"   "#ff717f"   "#223e9c"   "#aebea6"   "#edae11"   "#c74732"   "#6a73cf"  
# [57] "#edd064"   "#0eb0c8"   "#f2ccac"   "#868686"   "#339966"   "#83ba9e"   "#b12b23"   "#0f6657"  
# [65] "#f26115"   "#eb4601"  
# > 




```


#### Liver

```{r}
 netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("CD8 T",Liver_earlyname),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
```

#### Thymus

```{r}
 netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("CD8 T",Thymus_Earlyname),  comparison = c(4), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
```

#### Spleen
```{r}
netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = c(12),  comparison = c(5), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
```


##  Naive CD8 source


#### PBMC
```{r}
CD82others_PBMC_Early=netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",PBMC_Earlyname) , targets.use =c(1:31),  comparison = c(1), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_PBMC_Early.pdf", plot = CD82others_PBMC_Early)
```

```{r}
CD82others_PBMC_Early=netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",PBMC_Earlyname) , targets.use =c(1:31),  comparison = c(1), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_PBMC_Early.pdf", plot = CD82others_PBMC_Early)
```

#### PBMC_Late

```{r}
library(ggplot2)
library(CellChat)
# %%R -w 2000 -h 2000 -r 300
  CD82others_PBMC_Early=netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",PBMC_Earlyname) , targets.use =c(1:30),  comparison = c(1), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_PBMC_Early.pdf", plot = CD82others_PBMC_Early)
```

```{r}
library(ggplot2)
library(CellChat)
# %%R -w 2000 -h 2000 -r 300
CD82others_PBMC_late=netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",PBMC_latename) , targets.use =c(1:30),  comparison = c(2), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_PBMC_late.pdf", plot = CD82others_PBMC_late)
```


#### Liver
```{r}
 CD82others_Liver= netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",Liver_earlyname) , targets.use = c(1:33),  comparison = c(3), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_Liver.pdf", plot = CD82others_Liver)
```

#### Thymus
```{r}
ThymusCD8=netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",Thymus_Earlyname) , targets.use = c(1:33),  comparison = c(4), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_Thymus.pdf", plot =ThymusCD8)

```
#### Spleen
```{r}
SpleenCD8=netVisual_bubble(Organ_cellchat2, sources.use =grep("CD8 T",Spleen_Earlyname) , targets.use = c(1:33),  comparison = c(5), angle.x = 45,color.text = colorname2[c(8,13)])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/CD82others_SpleenCD8.pdf", plot =SpleenCD8)
```
```{r}
# P_Liver_abT <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("abT",Liver_earlyname),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/Liver_31_abT.pdf", plot = P_Liver_abT)

P_Thymus_abT <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("abT",Thymus_Earlyname),  comparison = c(4), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/Thymus_31_abT.pdf", plot = P_Thymus_abT)

P_Spleen_abT <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = grep("abT",Spleen_Earlyname),  comparison = c(5), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/Spleen_33_abT.pdf", plot = P_Spleen_abT)
```
## abT source

```{r}
# P_Liver_abT <- netVisual_bubble(Organ_cellchat2, sources.use =grep("abT",Liver_earlyname) , targets.use = c(1:33),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Liver_abT.pdf", plot = P_Liver_abT)
# 
# P_Thymus_abT <- netVisual_bubble(Organ_cellchat2, sources.use =grep("abT",Thymus_Earlyname) , targets.use = c(1:33),  comparison = c(4), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Thymus_abT.pdf", plot = P_Thymus_abT)
# 
# P_Spleen_abT <- netVisual_bubble(Organ_cellchat2, sources.use =grep("abT",Spleen_Earlyname) , targets.use = c(1:33),  comparison = c(5), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
# ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Spleen_abT.pdf", plot = P_Spleen_abT)


```
```{r}
P_Liver_earlyname_abT <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = grep("abT",Liver_earlyname),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/Liver_earlyname_abT.pdf", plot = P_Liver_earlyname_abT)

P_Spleen_Earlyname_abT <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = grep("abT",Spleen_Earlyname),  comparison = c(5), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S18/Spleen_Earlyname_abT.pdf", plot = P_Spleen_Earlyname_abT)

P_Thymus_Earlyname_abT <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = grep("abT",Thymus_Earlyname),  comparison = c(4), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S17/Thymus_Earlyname_abT.pdf", plot = P_Thymus_Earlyname_abT)
```
```{r}

```

### DPP end
```{r}

p1 <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("DPP",Liver_earlyname),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)


ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S19/Liver_earlyname_DPP.pdf", plot = p1)


p2 <- netVisual_bubble(Organ_cellchat2, sources.use =c(1:31) , targets.use = grep("DPP",Thymus_Earlyname),  comparison = c(4), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)


ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S19/Thymus_Earlyname_DPP.pdf", plot = p2)

## -----------------------------------------------------------------------------------------------------------
# netVisual_bubble(Organ_cellchat2, sources.use =c(1:33) , targets.use = grep("DPP",Spleen_Earlyname),  comparison = c(5), angle.x = 45,color.text = colorname2[8])
```

### DPP source
```{r}
# 生成第一个图
p1 <- netVisual_bubble(Organ_cellchat2, sources.use =grep("DPP",Liver_earlyname) , targets.use = c(1:33),  comparison = c(3), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)

# 保存第一个图为PDF文件
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S20/Liver_earlyname_DPP_reverse.pdf", plot = p1)

# 生成第二个图
p2 <- netVisual_bubble(Organ_cellchat2, sources.use =grep("DPP",Thymus_Earlyname) , targets.use = c(1:33),  comparison = c(4), angle.x = 45,color.text = colorname2[8])+scale_color_gradientn(colours = custom_cmap2)

# 保存第二个图为PDF文件
ggsave(filename = "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure3/S20/Thymus_Earlyname_DPP_reverse.pdf", plot = p2)


## -----------------------------------------------------------------------------------------------------------
# netVisual_bubble(Organ_cellchat2, sources.use =grep("DPP",Spleen_Earlyname) , targets.use = c(1:33),  comparison = c(5), angle.x = 45)



```

```{r}
library(jsonlite)


file_path <- "/home/maolp/Main_Gao_ScanpyProject20231130/HFB_script_in_save/Celltype_colors_dict_nonum.json"
colors_dict <- fromJSON(file_path)
colors_dict
```


```{r}

setdiff(names(colors_dict),unique(object.list[[1]]@meta$labels))
```
```{r}
setdiff(unique(object.list[[1]]@meta$labels),names(colors_dict))
```

```{r}
# %%R -w 8000 -h 3000 -r 300

num.link <- sapply(object.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
num.link 
weight.MinMax <- c(0,1000) 

gg <- list()
for (i in 1:length(object.list)) {
  gg[[i]] <- netAnalysis_signalingRole_scatter(object.list[[i]], 
                                               title = names(object.list)[i], weight.MinMax = weight.MinMax, label.size = 6,
                                               font.size.title = 30)+ylab("")+theme(
      axis.title.x = element_text(size=18), axis.text.x= element_text(size=18),
                                                                 axis.ticks.y = element_line(size = 2),  #
                                                            axis.text.y = element_text(size = 14)) +
    scale_y_continuous(breaks = seq(0, 60, by = 10))+coord_cartesian(ylim = c(0, 60),xlim = c(0, 18))+scale_x_continuous(breaks = seq(0, 18, by = 3))+scale_color_manual(values = colors_dict)
}
# patchwork::wrap_plots(plots = gg,ncol=5)
```

```{r}
for (i in 1:length(object.list)) {
  df <- prepare_data(object.list[[i]])
  
  gg[[i]] <- plot_data(df = df,
                       color.use = colors_dict,
                       dot.size = c(2, 6),
                       point.shape = c(21, 22, 24, 23, 25, 8, 3),
                       label.size = 6,
                       dot.alpha = 0.6,
                       xlabel = "Outgoing interaction strength",
                       ylabel = "",
                       title = names(object.list)[i],
                       font.size = 10,
                       font.size.title = 30,
                       do.label = TRUE,
                       show.legend = TRUE,
                       show.axes = TRUE,
                       weight.MinMax = c(0, 1000))
}


# gg[[1]]
```

```{r}
scPalette(nlevels(df$labels))
```



```{r}
"Group" %in% colnames(df)
breaks <- c(1, 250,  500, 750, 1000, 1250)  # 添加这一行
```
```{r}
# df <- prepare_data(object.list[[1]])
#  color.use = colors_dict
#  dot.size = c(2, 6)
#  point.shape = c(21, 22, 24, 23, 25, 8, 3)
#  label.size = 5
#  dot.alpha = 0.4
#  xlabel = "Outgoing interaction strength"
#  ylabel = "Incoming interaction strength"
#  title = names(object.list)[i]
#  font.size = 10
#  font.size.title = 30
#  do.label = TRUE
#  show.legend = TRUE
#  show.axes = TRUE
#  weight.MinMax = c(0, 1000)
# ggx <- ggplot(data = df, aes(x, y)) + geom_point(aes(size = Count, colour = labels, fill = labels))+ CellChat_theme_opts() + theme(text = element_text(size = font.size), legend.key.height = grid::unit(0.15, "in")) + labs(title = title, x = xlabel, y = ylabel) + theme(plot.title = element_text(size = font.size.title, face = "plain")) + theme(axis.line.x = element_line(size = 0.25), axis.line.y = element_line(size = 0.25))
# P1=ggx+ scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) + guides(fill = FALSE)+ scale_colour_manual(values = color.use, drop = FALSE) + guides(colour = FALSE) + scale_size_continuous(limits = weight.MinMax, range = dot.size)+ ggrepel::geom_text_repel(subset(df,labels %in% c("DPQ T","DPP T","CD56highCD16low NK","CX3CR1+ NK","CXCR6+ NK","Naïve CD8 T","NK T")),mapping = aes(label = labels, colour = labels), size = label.size, show.legend = F, segment.size = 0.2, segment.alpha = 0.5)+scale_y_continuous(limits = c(0,60))+scale_x_continuous(limits = c(0,20))+theme(aspect.ratio = 1)+   scale_size(range = c(1, 10), breaks = breaks, labels = breaks)
# P1
```


```{r}
breaks <- c(1, 250, 500, 750, 1000, 1250)
df <- prepare_data(object.list[[1]])
color.use = colors_dict
dot.size = c(1, 10)  # 修改点大小范围
point.shape = c(21, 22, 24, 23, 25, 8, 3)
label.size = 5
dot.alpha = 0.4
xlabel = "Outgoing interaction strength"
ylabel = "Incoming interaction strength"
title = names(object.list)[i]
font.size = 10
font.size.title = 30
do.label = TRUE
show.legend = TRUE
show.axes = TRUE
weight.MinMax = c(0, 1000)  # 调整最大权重以覆盖全部数据范围
ggx <- ggplot(data = df, aes(x, y)) +
  geom_point(aes(size = Count, colour = labels, fill = labels)) +
  CellChat_theme_opts() +
  theme(text = element_text(size = font.size), legend.key.height = grid::unit(0.15, "in")) +
  labs(title = title, x = xlabel, y = ylabel) +
  theme(plot.title = element_text(size = font.size.title, face = "plain")) +
  theme(axis.line.x = element_line(size = 0.25), axis.line.y = element_line(size = 0.25))
P1 = ggx +
  scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) +
  guides(fill = FALSE) +
  scale_colour_manual(values = color.use, drop = FALSE) +
  guides(colour = FALSE) +
  scale_size_continuous(limits = weight.MinMax, range = dot.size) +
  ggrepel::geom_text_repel(subset(df, labels %in% c("DPQ T", "DPP T", "CD56highCD16low NK", "CX3CR1+ NK", "CXCR6+ NK", "Naïve CD8 T", "NK T")), mapping = aes(label = labels, colour = labels), size = label.size, show.legend = FALSE, segment.size = 0.2, segment.alpha = 0.5) +
  scale_y_continuous(limits = c(0, 60)) +
  scale_x_continuous(limits = c(0, 20)) +
  theme(aspect.ratio = 1) +
  scale_size(range = dot.size, breaks = breaks, labels = breaks)  # 保证使用修改后的点大小范围
P1
```

```{r}
P1$data
```




```{r}
# library(dplyr)
# 
# # 筛选特定标签的数据
# filtered_df <- df %>% 
#   filter(labels %in% c("DPQ T", "DPP T", "CD56highCD16low NK", "CX3CR1+ NK", "CXCR6+ NK", "Naïve CD8 T", "NK T"))
# 
# # 使用筛选后的数据进行绘图
# ggx <- ggplot(data = filtered_df, aes(x, y)) +
#   geom_point(aes(size = SizeCategory, colour = labels, fill = labels)) +
#   theme_minimal() +
#   ggrepel::geom_text_repel(aes(label = labels), 
#                            size = label.size, show.legend = FALSE, 
#                            segment.size = 0.2, segment.alpha = 0.5)
# ggx <- ggplot(data = df, aes(x, y)) +
#   geom_point(aes(size = Count, colour = labels, fill = labels)) +
#   CellChat_theme_opts() +
#   theme(text = element_text(size = font.size),
#         legend.key.height = grid::unit(0.15, "in"),
#         plot.title = element_text(size = font.size.title, face = "plain"),
#         axis.line.x = element_line(size = 0.25),
#         axis.line.y = element_line(size = 0.25)) +
#   labs(title = title, x = xlabel, y = ylabel) +
#   scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) +
#   guides(fill = FALSE, colour = FALSE) +
#   scale_colour_manual(values = color.use, drop = FALSE) +
#   scale_size_continuous(breaks = breaks, labels = labels, range = c(1, 3)) +
#   ggrepel::geom_text_repel(aes(label = labels), subset = .(labels %in% c("DPQ T","DPP T","CD56highCD16low NK","CX3CR1+ NK","CXCR6+ NK","Naïve CD8 T","NK T")),
#                            size = label.size, show.legend = FALSE, segment.size = 0.2, segment.alpha = 0.5) +
#   scale_y_continuous(limits = c(0, 60)) +
#   scale_x_continuous(limits = c(0, 20)) +
#   theme(aspect.ratio = 1)
#   
# P2 <- ggx
# P2
```

```{r}
df <- prepare_data(object.list[[3]])
 color.use = colors_dict
 dot.size =  c(1, 10)
 point.shape = c(21, 22, 24, 23, 25, 8, 3)
 label.size = 5
 dot.alpha = 0.4
 xlabel = "Outgoing interaction strength"
 ylabel = "Incoming interaction strength"
 title = names(object.list)[i]
 font.size = 10
 font.size.title = 30
 do.label = TRUE
 show.legend = TRUE
 show.axes = TRUE
 weight.MinMax = c(0, 1250)
ggx <- ggplot(data = df, aes(x, y)) + geom_point(aes(size = Count, colour = labels, fill = labels))+ CellChat_theme_opts() + theme(text = element_text(size = font.size), legend.key.height = grid::unit(0.15, "in")) + labs(title = title, x = xlabel, y = ylabel) + theme(plot.title = element_text(size = font.size.title, face = "plain")) + theme(axis.line.x = element_line(size = 0.25), axis.line.y = element_line(size = 0.25))
P3=ggx+ scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) + guides(fill = FALSE)+ scale_colour_manual(values = color.use, drop = FALSE) + guides(colour = FALSE) + scale_size_continuous(limits = weight.MinMax, range = dot.size)+ ggrepel::geom_text_repel(subset(df,labels %in% c("DPP T","CD56highCD16low NK","CX3CR1+ NK","CXCR6+ NK","Naïve CD8 T","NK T")),mapping = aes(label = labels, colour = labels), size = label.size, show.legend = F, segment.size = 0.2, segment.alpha = 0.5)+scale_y_continuous(limits = c(0,60))+scale_x_continuous(limits = c(0,20))+theme(aspect.ratio = 1)+  scale_size(range = dot.size, breaks = breaks, labels = breaks)  
P3

```
```{r}
df <- prepare_data(object.list[[4]])
 color.use = colors_dict
 dot.size = c(1, 10)
 point.shape = c(21, 22, 24, 23, 25, 8, 3)
 label.size = 5
 dot.alpha = 0.4
 xlabel = "Outgoing interaction strength"
 ylabel = "Incoming interaction strength"
 title = names(object.list)[i]
 font.size = 10
 font.size.title = 30
 do.label = TRUE
 show.legend = TRUE
 show.axes = TRUE
 weight.MinMax = c(0, 1250)
ggx <- ggplot(data = df, aes(x, y)) + geom_point(aes(size = Count, colour = labels, fill = labels))+ CellChat_theme_opts() + theme(text = element_text(size = font.size), legend.key.height = grid::unit(0.15, "in")) + labs(title = title, x = xlabel, y = ylabel) + theme(plot.title = element_text(size = font.size.title, face = "plain")) + theme(axis.line.x = element_line(size = 0.25), axis.line.y = element_line(size = 0.25))
P4=ggx+ scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) + guides(fill = FALSE)+ scale_colour_manual(values = color.use, drop = FALSE) + guides(colour = FALSE) + scale_size_continuous(limits = weight.MinMax, range = dot.size)+ ggrepel::geom_text_repel(subset(df,labels %in% c("DPQ T","DPP T","CD56highCD16low NK","CX3CR1+ NK","CXCR6+ NK","Naïve CD8 T","NK T")),mapping = aes(label = labels, colour = labels), size = label.size, show.legend = F, segment.size = 0.2, segment.alpha = 0.5)+scale_y_continuous(limits = c(0,60))+scale_x_continuous(limits = c(0,20))+theme(aspect.ratio = 1)+   scale_size(range = dot.size, breaks = breaks, labels = breaks)  
P4
```
```{r}
df <- prepare_data(object.list[[5]])
 color.use = colors_dict
 dot.size = c(1, 10)
 point.shape = c(21, 22, 24, 23, 25, 8, 3)
 label.size = 5
 dot.alpha = 0.4
 xlabel = "Outgoing interaction strength"
 ylabel = "Incoming interaction strength"
 title = names(object.list)[i]
 font.size = 10
 font.size.title = 30
 do.label = TRUE
 show.legend = TRUE
 show.axes = TRUE
 weight.MinMax = c(0, 1250)
 ggx <- ggplot(data = df, aes(x, y)) + geom_point(aes(size = Count, colour = labels, fill = labels))+ CellChat_theme_opts() + theme(text = element_text(size = font.size), legend.key.height = grid::unit(0.15, "in")) + labs(title = title, x = xlabel, y = ylabel) + theme(plot.title = element_text(size = font.size.title, face = "plain")) + theme(axis.line.x = element_line(size = 0.25), axis.line.y = element_line(size = 0.25))
P5=ggx+ scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) + guides(fill = FALSE)+ scale_colour_manual(values = color.use, drop = FALSE) + guides(colour = FALSE) + scale_size_continuous(limits = weight.MinMax, range = dot.size)+ ggrepel::geom_text_repel(subset(df,labels %in% c("DPQ T","DPP T","CD56highCD16low NK","CX3CR1+ NK","CXCR6+ NK","Naïve CD8 T","NK T")),mapping = aes(label = labels, colour = labels), size = label.size, show.legend = F, segment.size = 0.2, segment.alpha = 0.5)+scale_y_continuous(limits = c(0,60))+scale_x_continuous(limits = c(0,20))+theme(aspect.ratio = 1)+ scale_size(range = dot.size, breaks = breaks, labels = breaks)  
P5
```




```{r}
library(patchwork)
library(ggplot2)

# Assuming 'gg' is a list of ggplot objects
p <- patchwork::wrap_plots(plots = list(P1,P2,P3,P4,P5), ncol = 5)
```


```{r}
ggsave("Figure202403/Large_plot2.pdf", p, width = 30, height = 10, units = "in", dpi = 300)
# Save the plot to a file
ggsave("Figure202403/Large_plot2.png", p, width = 30, height = 10, units = "in", dpi = 300)
```

```{r}
pdf("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Main_Figure3/Figure3A.pdf",width=40,height=10)
print(patchwork::wrap_plots(plots = gg,ncol=5))
dev.off()
```



```{r}
Readfuck<-function(i){
  df <- prepare_data(object.list[[i]])
 color.use = colors_dict
 dot.size = c(1, 10)
 point.shape = c(21, 22, 24, 23, 25, 8, 3)
 label.size = 5
 dot.alpha = 0.4
 xlabel = "Outgoing interaction strength"
 ylabel = "Incoming interaction strength"
 title = names(object.list)[i]
 font.size = 10
 font.size.title = 30
 do.label = TRUE
 show.legend = TRUE
 show.axes = TRUE
 weight.MinMax = c(0, 1000)
 df
 df$SizeCategory <- cut(df$Count, 
                       breaks = c(0, 250, 500, 750, 1250),
                       labels = c(1, 4, 7, 10),
                       include.lowest = TRUE)
ggx <- ggplot(data = df, aes(x, y)) + geom_point(aes(size = SizeCategory, colour = labels, fill = labels))+ CellChat_theme_opts() + theme(text = element_text(size = font.size), legend.key.height = grid::unit(0.15, "in")) + labs(title = title, x = xlabel, y = ylabel) + theme(plot.title = element_text(size = font.size.title, face = "plain")) + theme(axis.line.x = element_line(size = 0.25), axis.line.y = element_line(size = 0.25))

df$Count
P2=ggx+ scale_fill_manual(values = ggplot2::alpha(color.use, alpha = dot.alpha), drop = FALSE) + guides(fill = FALSE)+ scale_colour_manual(values = color.use, drop = FALSE) + guides(colour = FALSE) +
  # scale_size_continuous(limits = weight.MinMax, range = dot.size)+
  ggrepel::geom_text_repel(subset(df,labels %in% c("DPQ T","DPP T","CD56highCD16low NK","CX3CR1+ NK","CXCR6+ NK","Naïve CD8 T","NK T")),mapping = aes(label = labels, colour = labels), size = label.size, show.legend = F, segment.size = 0.2, segment.alpha = 0.5)+ scale_size_manual(values = c(1, 4, 7, 10), labels = c("250", "500", "750", "1000"))  +theme(aspect.ratio = 1)+
scale_y_continuous(limits = c(0,60))+scale_x_continuous(limits = c(0,20))
# +scale_x_continuous(limits = c(0,20))+theme(aspect.ratio = 1)+   scale_size(range = c(1,10), breaks = breaks, labels = breaks)  
P2
return(P2)
}

Readfuck(5)

library(patchwork)
library(ggplot2)

# Assuming 'gg' is a list of ggplot objects
p <- patchwork::wrap_plots(plots = list(Readfuck(1),Readfuck(2),Readfuck(3),Readfuck(4),Readfuck(5)), ncol = 5)
```


```{r}
ggsave("Figure202403/Large_plot3.pdf", p, width = 30, height = 10, units = "in", dpi = 300)
# Save the plot to a file
ggsave("Figure202403/Large_plot3.png", p, width = 30, height = 10, units = "in", dpi = 300)
```