---
title: "Untitled"
output: html_document
date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```

```{r}
library(tidyverse)
# library(Seurat)
library(CellChat)
```
```{r}
load("/data5/maolp/Main_Gao_ScanpyProject20231130/HFB_script_in_Jupyter/HFB0403CellChat/Figure3_Cellchat2/Data/PBMC_cellchat.RData")
```

```{r}
adata1 = readRDS("/home/maolp/data5/Gaofeng_All_matrix/Allcount/All_scanpyData/Data/scdata.rds")
```

```{r}
# %%R
# 
library(dplyr)
library(stringr)


adata1@meta.data <- adata1@meta.data %>% mutate(
  Category = case_when(
    # Identify the initial letter
    str_detect(AdjustedID, "^B") ~ "PBMC",
    str_detect(AdjustedID, "^L") ~ "Liver",
    str_detect(AdjustedID, "^T") ~ "Thymus",
    str_detect(AdjustedID, "^S") ~ "Spleen",
    TRUE ~ "Other"  # for any other cases
  ),
  NumericPart = as.numeric(str_extract(AdjustedID, "\\d+\\.\\d+")),  # extract the numeric part
  Stage = ifelse(NumericPart <= 26, "Early", "Late")  # classify as "Early" or "Late"
)
adata1@meta.data$GroupStat<-paste0(adata1@meta.data$Category,"_",adata1@meta.data$Stage)
```

```{r}
# unique(adata1@meta.data$GroupStat)
```
```{r}
# sort(unique(as.character(adata1@meta.data$AdjustedID)))
```

```{r}
adata1@meta.data$AdjustedID<-factor(adata1@meta.data$AdjustedID,levels = sort(unique(as.character(adata1@meta.data$AdjustedID))))
levels(adata1@meta.data$AdjustedID)
```

```{r}
cell_types_list = c("HSC_MPP",
    
    "MEP",
    "MEMP",
    "Pro-B",
    "Large pre-B",
    "Small pre-B",
    
    "CXCR5- Na誰ve B",
    "CXCR5+ Na誰ve B",

      "DN(Q) T",
    "DP(P) T",
 
    "DP(Q) T",
    
    "Treg",
    
    "Cycling Treg",
  
    "Na誰ve CD4 T",
    "Na誰ve CD8 T",
    "abT(entry)",
    
    
    'Tem',
        "Th17like_INNATE_T",
        'NK T',
        "Gamma Delta V1 T",
    "Gamma Delta V2 T",
    



    "GNG4 +CD8aa+T",

     "ILC2/3",


    "CX3CR1+ NK",
    
    "CXCR6+ NK",
    "CD56highCD16low NK",

    
    "Myeloid-CD177",
    "Classical Monocytes",
    "CD14+PPBP+ Monocytes",
    'Macrophages',
    "DC1",
    "DC2",
    "pDC",

    "Megakaryocytes",

    
    "Early_ERY",
    "Mid_ERY",
    "Late_ERY",

    "Endothelial cells",
     "Others"


)

```


```{r}
# table(adata1@meta.data$GroupStat,adata1@meta.data$AdjustedID)

```
```{r}
# subPBMC=subset(adata1,New_Body=="PBMC")
# celltype=names(table(subPBMC@meta.data$Last_cell_type )[table(subPBMC@meta.data$Last_cell_type )>100])
```
```{r}
# celltype<-celltype[-which(celltype=="Others")]
```

```{r}
# subPBMCearly=subset(adata1,GroupStat=="PBMC_Early")
# subPBMCearly2=subset(subPBMCearly,Last_cell_type %in% celltype)
```
```{r}
# subPBMClate=subset(adata1,GroupStat=="PBMC_Late")
# subPBMlate2=subset(subPBMClate,Last_cell_type %in% celltype)


```
```{r}
# subPBMClate@meta.data
```
```{r}
unique(subPBMCearly2@meta.data$Last_cell_type)
```

```{r}
setdiff(unique(subPBMCearly2@meta.data$Last_cell_type),unique(subPBMlate2@meta.data$Last_cell_type))
setdiff(unique(subPBMlate2@meta.data$Last_cell_type),unique(subPBMCearly2@meta.data$Last_cell_type))
```
```{r}
subPBMlate2@meta.data$Last_cell_type<-factor(subPBMlate2@meta.data$Last_cell_type,levels = cell_types_list)
subPBMCearly2@meta.data$Last_cell_type<-factor(subPBMCearly2@meta.data$Last_cell_type,levels = cell_types_list)
```

```{r}
subPBMCadata1=subset(subPBMC,Last_cell_type %in% celltype)
```


```{r}
# %%R
process_cellchat233 <- function(adata,  id_value) {
  subset_data <- subset(adata, GroupStat== id_value)
  data.pbmc <- subset_data@assays$RNA@data
  # Use cell_type_label as the name of the column to use for group labels
  cellmeta <- data.frame(group = as.character(subset_data$Last_cell_type), row.names = names(subset_data$Last_cell_type))
#   print("test3")
  print(paste("Cellmeta rows: ", nrow(cellmeta)))
  print(paste("Subset data cells: ", length(subset_data@meta.data$Last_cell_type)))
  cellchat <- createCellChat(object = data.pbmc)
  cellchat <- addMeta(cellchat, meta = cellmeta, meta.name = "labels")
  cellchat <- setIdent(cellchat, ident.use = "labels")
  
  CellChatDB <- CellChatDB.human
  CellChatDB.use <- subsetDB(CellChatDB, search = "Cell-Cell Contact", key = "annotation")
  cellchat@DB <- CellChatDB.use
  
  cellchat <- subsetData(cellchat)
  cellchat <- identifyOverExpressedGenes(cellchat)
  cellchat <- identifyOverExpressedInteractions(cellchat)
  cellchat <- projectData(cellchat, PPI.human)

  cellchat <- computeCommunProb(cellchat)
  cellchat <- computeCommunProbPathway(cellchat)
  cellchat <- aggregateNet(cellchat)
  
  return(cellchat)
}

# Get a list of all unique AdjustedID values
# # adjusted_ids <- unique(adata1$AdjustedID)
# GroupStat_ids <- c( "PBMC_Early","PBMC_Late"  )
# PBMC_Early=process_cellchat233(subadata1,"PBMC_Early")

```

```{r}
rm(adata1)
```
