---
title: "Untitled"
output: html_document
date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
GS<-readRDS("/home/maolp/Allcount/All_scanpyData/Cellchat/Organ_results_rmcl.rds")
```

```{r}
GroupStat_ids <- c( "PBMC_Early","PBMC_Late" ,"Liver_Early","Thymus_Early", "Spleen_Early")
```

```{r}
Organ_cellchat<- mergeCellChat(GS, add.names =GroupStat_ids)
```

```{r}
results2=GS
# unique(adata1$AdjustedID)
# str(results2[[1]])
# 提取每个列表元素的第一个列名中 _ 前面的部分
result <- lapply(1:32, function(x) {
    col_name <- colnames(results2[[1]]@data)
    strsplit(col_name, "_")[[1]][1]
})


result_vector <- unlist(result)


print(result_vector)
```
```{r}
# merged_cellchat2 <- mergeCellChat(results2, add.names =unique_data$AdjustedID)
```

```{r}
gg1 <- compareInteractions(Organ_cellchat , show.legend = F, group = c(1,2,3,4,5))+scale_fill_manual(values = c("#FFA300","#F6313E", "#fb862b", "#0eb0c8", "#6a73cf"))
gg2 <- compareInteractions(Organ_cellchat , show.legend = F, group = c(1,2,3,4,5), measure = "weight")+scale_fill_manual(values = c("#FFA300","#F6313E", "#fb862b", "#0eb0c8", "#6a73cf"))
gg1 + gg2
```

```{r}
Organ_results=GS
object.list=Organ_results
object.list <- lapply(object.list, function(x) netAnalysis_computeCentrality(x, slot.name = "netP"))
```


```{r}
names(object.list)<-GroupStat_ids 
```
```{r}
library(ggsci)
cols01 <- c("#f49128", "#194a55", "#187c65", "#f26115", "#c29f62", "#83ba9e")
cols02 <- c("#c62d17", "#023f75", "#ea894e", "#266b69", "#eb4601", "#f6c619")
cols03 <- c("#fa6e01", "#2f2f2f", "#972b1d", "#e6a84b", "#4c211b", "#ff717f")
cols04 <- c("#223e9c", "#b12b23", "#aebea6", "#edae11", "#0f6657", "#c74732")
cols05 <- c("#6a73cf", "#edd064", "#0eb0c8", "#f2ccac", "#a1d5b9", "#e1abbc")

all_colors <- c(cols01, cols02, cols03, cols04, cols05)
all_colors
colorname2=c(pal_futurama()(3),"#46A040","#00AF99" ,"#F6313E", "#FFA300","#2f2f2f",  "#FFC179", 
"#FF5A00", "#663366","#FF6666","#8F1336", "#0081C9", "#001588", "#CC0033",
"#CC9966","#CC0033","#999933","#009966","#CCCC33","#CCFF99","#0eb0c8","#993333","#333366",
"#490C65", "#BA7FD0","#A6CEE3", "#1F78B4", "#DE77AE", "#B2DF8A", "#006D2C", "#B5AD64",
"#9DA8E2","#91C392", "#194a55", "#187c65", "#c29f62","#f49128","#c62d17", "#333329",
"#023f75", "#ea894e", "#266b69",  "#e1abbc","#f6c619","#fa6e01", "#972b1d", "#e6a84b", "#4c211b", "#ff717f","#223e9c", 
"#aebea6", "#edae11", "#c74732", "#6a73cf", "#edd064" , 
"#0eb0c8", "#f2ccac" ,"#868686","#339966", "#83ba9e", "#b12b23", "#0f6657","#f26115","#eb4601")
colorname3=colorname2
length(colorname3)
```
```{r}
library(jsonlite)


file_path <- "/home/maolp/Allcount/Last_All_scanpyData/ColorDict/Celltype_colors_dict_nonum.json"
colors_dict <- fromJSON(file_path)
# colors_dict
```

```{r}
num.link <- sapply(object.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
num.link 
weight.MinMax <- c(0,643) 

gg <- list()
for (i in 1:length(object.list)) {
  gg[[i]] <- netAnalysis_signalingRole_scatter(object.list[[i]], 
                                               title = names(object.list)[i], weight.MinMax = weight.MinMax, label.size = 6,
                                               font.size.title = 30)
#     ylab("")+theme(
#       axis.title.x = element_text(size=18), axis.text.x= element_text(size=18),
#                                                                  axis.ticks.y = element_line(size = 2),  #
#                                                             axis.text.y = element_text(size = 14)) + scale_color_manual(values = colors_dict)+
#     scale_y_continuous(breaks = seq(0, 50, by = 10))+coord_cartesian(ylim = c(0, 50),xlim = c(0, 18))+scale_x_continuous(breaks = seq(0, 18, by = 3))
}
```


```{r}

```

```{r}
# %%R -w 6000 -h 3000 -r 300
library(patchwork)


for (i in 2:5) {
  gg[[i]] <- gg[[i]] + guides(color = FALSE, fill = FALSE)
}


p <- wrap_plots(plots = gg, ncol = 5)

print(p)
```
```{r}
pdf("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Main_Figure3/Figure3A_organ_cellchat.pdf",width=40,height=10)
print(p)
dev.off()
```

```{r}
# object.list=GroupStat_res2
object.list[[1]]=netAnalysis_computeCentrality(object.list[[1]], slot.name = "netP") 
object.list[[2]]=netAnalysis_computeCentrality(object.list[[2]], slot.name = "netP") 
object.list[[3]]=netAnalysis_computeCentrality(object.list[[3]], slot.name = "netP") 
object.list[[4]]=netAnalysis_computeCentrality(object.list[[4]], slot.name = "netP") 
object.list[[5]]=netAnalysis_computeCentrality(object.list[[5]], slot.name = "netP") 
```

```{r}
num.link <- sapply(object.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
num.link 
weight.MinMax <- c(0,643) 

gg <- list()
for (i in 1:length(object.list)) {
  gg[[i]] <- netAnalysis_signalingRole_scatter(object.list[[i]], 
                                               title = names(object.list)[i], weight.MinMax = weight.MinMax, label.size = 6,
                                               font.size.title = 30)
#     ylab("")+theme(
#       axis.title.x = element_text(size=18), axis.text.x= element_text(size=18),
#                                                                  axis.ticks.y = element_line(size = 2),  #
#                                                             axis.text.y = element_text(size = 14)) + scale_color_manual(values = colors_dict)+
#     scale_y_continuous(breaks = seq(0, 50, by = 10))+coord_cartesian(ylim = c(0, 50),xlim = c(0, 18))+scale_x_continuous(breaks = seq(0, 18, by = 3))
}

```
```{r}
pdf("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Main_Figure3/Figure3A_organ_cellchat.pdf",width=40,height=10)
print(patchwork::wrap_plots(plots = p,ncol=5))
dev.off()
```
```{r}
gg1 <- compareInteractions(Organ_cellchat , show.legend = F, group = c(1:32))
```

```{r}
library(tidyverse)

process_data <- function(data) {
  data <- data %>%
    separate(dataset, into = c("part1", "part2"), sep = "_") %>%
    mutate(
      Organ = substr(part1, 1, 1),
      Week = substr(part1, 2, 5)
    ) %>%
    arrange(Organ,Week) %>%
    mutate(
      Stage = ifelse(as.numeric(Week) > 26, "Late", "Early")
    )
  
  return(data)
}
```


```{r}
data1 <- process_data(gg1$data)
data1$Organ_Stage <-paste0(data1$Organ,'_',data1$Stage)
data1_PBMC=data1[grep('B',data1$Organ),]
print(data1)
```

```{r}
# %%R -w 1600 -h 1200 -r 300

library(ggplot2)
library(ggpubr)

data1$Organ_Stage<-factor(data1$Organ_Stage,level=c("B_Early", "B_Late", "L_Early","T_Early","S_Early"))
p2 <- ggplot(data1, aes(x = Organ_Stage, y = count)) +
geom_boxplot(alpha = .5) +
    geom_point(position = position_jitter(seed = 2023, width = .25),
               aes(color =Organ_Stage, shape =Organ_Stage ), alpha = .4, size = 3) +
    theme(panel.grid = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_blank(),
          axis.line = element_line(color = "black"),
          axis.text.x = element_text(size = 12, angle = 45, hjust = 1), 
          axis.text.y = element_text(size = 12),
          plot.title = element_text(hjust = 0.5),
          legend.title = element_blank(), 
          legend.key = element_blank()) +
    scale_fill_futurama() +
    scale_color_futurama()

my_comparisons <- list(
  c("B_Early", "B_Late"),
  c("B_Early", "L_Early"),
  c("B_Early", "S_Early"),
  c("B_Early", "T_Early"),
  c("B_Late", "L_Early"),
  c("B_Late", "S_Early"),
  c("B_Late", "T_Early"),
  c("L_Early", "S_Early"),
  c("L_Early", "T_Early"),
  c("S_Early", "T_Early")
)

p2 <- p2 + stat_compare_means(comparisons = my_comparisons, label = "p.signif", tip.length = 0.01) + theme_minimal() +
  theme(panel.grid = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1), 
        axis.text.y = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(), 
        legend.key = element_blank()) +
  labs(x = '', y = '', title = 'Number of inferred interactions')+scale_fill_manual(values = c("#FFA300","#F6313E", "#fb862b", "#0eb0c8", "#6a73cf"))

print(p2)
ggsave(plot=p2,"/home/maolp/Allcount/All_scanpyData/Cellchat/PBMC_cellchat_boxplot_inferred_interactions.pdf",width=4,height=4)

```

```{r}
# %%R -w 8000 -h 3000 -r 300

num.link <- sapply(object.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
num.link 
weight.MinMax <- c(0,643) 

gg <- list()
for (i in 1:length(object.list)) {
  gg[[i]] <- netAnalysis_signalingRole_scatter(object.list[[i]], 
                                               title = names(object.list)[i], weight.MinMax = weight.MinMax, label.size = 6,
                                               font.size.title = 30)
#     ylab("")+theme(
#       axis.title.x = element_text(size=18), axis.text.x= element_text(size=18),
#                                                                  axis.ticks.y = element_line(size = 2),  #
#                                                             axis.text.y = element_text(size = 14)) + scale_color_manual(values = colors_dict)+
#     scale_y_continuous(breaks = seq(0, 50, by = 10))+coord_cartesian(ylim = c(0, 50),xlim = c(0, 18))+scale_x_continuous(breaks = seq(0, 18, by = 3))
}
```


```{r}
pdf("/home/maolp/Allcount/Last_All_scanpyData/Cellchat/Organall.pdf",width=40,height=10)
patchwork::wrap_plots(plots = gg,ncol=5)
dev.off()
```

