---
title: "Untitled"
format: html
editor: visual
---

```{r}
rm(list = ls())
```


```{r}
library(dplyr)
library(ggplot2)
```

```{r}
results_by_module=readRDS('/home/maolp/data5/Gaofeng_All_matrix/Allcount//All_scanpyData/Last_Hotspot/Early_results_by_module_Go_results_by_module.RDS')
allmods=read.csv("/home/maolp/data5/Gaofeng_All_matrix/Allcount//All_scanpyData/Last_Hotspot/hsPBMC_Early_all_mods.csv")

```


```{r}
Earlymods=read.csv("/home/maolp/data5/Gaofeng_All_matrix/Allcount//All_scanpyData/Last_Hotspot/hsPBMC_Early_all_mods.csv")
Latemods=read.csv("/home/maolp/data5/Gaofeng_All_matrix/Allcount//All_scanpyData/Last_Hotspot/hsPBMC_Late_all_mods.csv")
```

```{r}
ErM=table(Earlymods$Module) %>% as.data.frame()
ErM$Group<-"Early"
```
```{r}
LateM=table(Latemods$Module)%>% as.data.frame()
LateM$Group<-"Late"
ELsum=rbind(ErM,LateM)
library(ggsci)
colnames(ELsum)=c("Lineage","Freq","Group")

```


```{r}
system("mkdir -p /home/Lipeng/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure2/Sup2others")
ggplot(ELsum)+geom_col(aes(Lineage,Freq,fill=Group),stat='identity', position=position_dodge())+scale_fill_jama()+theme_classic()
ggsave("/home/Lipeng/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure2/Sup2others/S2col.pdf")
system("cp /home/Lipeng/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Sup_Figure2/Sup2others/S2col.pdf Data ")
```

```{r}
source("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_script_in_save/util.R")
```

```{r}
system("mkdir -p Data/Enrich")
```

```{r}
datalist=list()
for (i  in unique(Earlymods$Module) ) {
  tem=setdiff(subset(Earlymods,Module==i)$X,subset(Latemods,Module==i)$X)
  print(tem)
  system(paste0("mkdir -p ","Data/Enrich","/",i))
  write.csv(tem,paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_gene.csv"))
  datalist[[i]]=perform_GO(tem)
 library(ggsci)
if(!is.null(datalist[[i]])){
  P1=dotplot(datalist[[i]], showCategory=10, title=paste0(i,"GO All"))+scale_color_viridis_b()
}
ggsave(plot=P1,paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_enrich.pdf"))
  write.csv(datalist[[i]],paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_enrich.csv"))
}

```

```{r}
nb=data.frame()
for (i  in unique(Earlymods$Module) ) {
  tem=setdiff(subset(Earlymods,Module==i)$X,subset(Latemods,Module==i)$X)
  ten=data.frame(Group=paste0("E_",i),Number=length(tem))
  nb=rbind(nb,ten)
}
nb
```


```{r}
for (i  in unique(Earlymods$Module) ) {
  tem=setdiff(subset(Latemods,Module==i)$X,subset(Earlymods,Module==i)$X)

 ten=data.frame(Group=paste0("L_",i),Number=length(tem))
  nb=rbind(nb,ten)
}
nb
```
```{r}
nb$Group2<-substring(nb$Group,1,1)
nb$Sample<-gsub("E_","",nb$Group) %>% gsub("L_","",.)
```

```{r}
ggplot(nb)+geom_bar(aes(Sample,Number,fill=Group2),stat="identity", position=position_dodge())+theme_classic()+xlab("")+scale_fill_d3()
```
```{r}

```

```{r}
datalist2=list()

perform_GO2=function(gene_df) {
  

    

    enrichGO_result <- enrichGO(gene_df, OrgDb = org.Hs.eg.db, ont = 'ALL', 
                                pAdjustMethod = 'BH', pvalueCutoff = 0.05, 
                                qvalueCutoff = 0.1, keyType = 'SYMBOL')
    
    
    return(enrichGO_result)
}
for (i  in unique(Earlymods$Module) ) {
  tem=setdiff(subset(Earlymods,Module==i)$X,subset(Latemods,Module==i)$X)

  # print(tem)
  # system(paste0("mkdir -p ","Data/Enrich","/",i))
  # write.csv(tem,paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_gene.csv"))
  datalist2[[paste0("E_",i)]]=perform_GO(tem)
  
#  library(ggsci)
# if(!is.null(datalist[[i]])){
#   P1=dotplot(datalist[[i]], showCategory=10, title=paste0(i,"GO All"))+scale_color_viridis_b()
# }
# ggsave(plot=P1,paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_enrich.pdf"))
#   write.csv(datalist[[i]],paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_enrich.csv"))
}

for (i  in unique(Earlymods$Module) ) {
  tem=setdiff(subset(Latemods,Module==i)$X,subset(Earlymods,Module==i)$X)

  # print(tem)
  # system(paste0("mkdir -p ","Data/Enrich","/",i))
  # write.csv(tem,paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_gene.csv"))
  datalist2[[paste0("L_",i)]]=perform_GO(tem)
  
#  library(ggsci)
# if(!is.null(datalist[[i]])){
#   P1=dotplot(datalist[[i]], showCategory=10, title=paste0(i,"GO All"))+scale_color_viridis_b()
# }
# ggsave(plot=P1,paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_enrich.pdf"))
#   write.csv(datalist[[i]],paste0("Data/Enrich","/",i,"/",i,"_diff_eraly_late_enrich.csv"))
}

```

```{r}
dotplot(datalist2[[3]])
```

```{r}
names(datalist2)
i="STEM" 
setdiff(subset(Latemods,Module==i)$X,subset(Earlymods,Module==i)$X)

```

```{r}

```

```{r}
i="E_ERY"
head(datalist2[[i]])
datafr=data.frame()
for (i in names(datalist2)) {
  tem1=head(arrange(datalist2[[i]],desc(Count)))[1,]
  tem1$Group<-i
  datafr=rbind(datafr,tem1)
  
  
}
  datafr
```
```{r}
datafr1=na.omit( datafr)
datafr1$Count
datafr1$Group<-factor(datafr1$Group,levels = c("E_ERY"  , "E_MK"   , "E_Mono" ,"E_Bcell", "E_NK"   , "E_Tcell"  ,"E_STEM",  "L_MK"   , "L_Mono" ,"L_Bcell" ,"L_NK" ,   "L_Tcell" ))
```

```{r}
library(RColorBrewer)
colorsseq1 <-c("#f7fbff","#deebf7","#c6dbef","#9ecae1","#6baed6","#4292c6","#2171b5","#084594")
col_fun1 = c("#c6dbef", "#9c76c2","#272d74")
P1=ggplot(datafr1)+geom_point(aes(Group,Description,size=Count,color=p.adjust))+theme_dose() + 
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
    axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1)
  )+xlab("")+ylab("")+ scale_size_continuous(breaks = c(3, 6, 9))+scale_color_gradientn(colours = rev(col_fun1) )+theme(aspect.ratio = 1)
P1
ggsave(plot =P1 ,"Data2/Enrich/Figure2_head1_EarlyandLate_GO.pdf",width = 10,height = 6)
```
```{r}

```

```{r}
datalist=list()
for (i  in unique(Earlymods$Module) ) {
  tem=setdiff(subset(Latemods,Module==i)$X,subset(Earlymods,Module==i)$X)
  # print(tem)
  system(paste0("mkdir -p ","Data2/Enrich","/",i))
  write.csv(tem,paste0("Data2/Enrich","/",i,"/",i,"_diff_late_ealy_gene.csv"))
  datalist[[i]]=perform_GO(tem)
#  library(ggsci)
# if(!is.null(datalist[[i]])){
#   P1=dotplot(datalist[[i]], showCategory=10, title=paste0(i,"GO All"))+scale_color_viridis_b()
#   ggsave(plot=P1,paste0("Data2/Enrich","/",i,"/",i,"_diff_late_ealy_enrich.pdf"))
# }
#   
# 
# write.csv(datalist[[i]],paste0("Data2/Enrich","/",i,"/",i,"_diff_late_ealy_enrich.csv"))
}
```
```{r}

```

```{r}
i=1
if(!is.null(datalist[[i]])){
  P1=dotplot(datalist[[i]],show=20)+scale_color_viridis_b()
}
```
```{r}

```



```{r}
write.csv(Earlymods,"Data/Earlymods.csv")
write.csv(Latemods,"Data/Latemods.csv")
```

```{r}
library(tidyverse)

table(allmods$Module)%>% as.data.frame()-> modegene
modegene$Var2<-factor(paste0('module',modegene$Var1),level=paste0('module',modegene$Var1))

vlines <- 0.5 + seq_len(nlevels(factor(modegene$Var1))) 
print(vlines)
ggplot( modegene)+geom_col(aes(Var2,Freq),fill="black")+  theme_bw(base_size = 16) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank())+ylab('Gene Number')+xlab("")
```

```{r}
Metaenrich=read.csv("Metaenrich.csv")
```
```{r}
Early=Metaenrich[grep("Early",Metaenrich$X),]
```
```{r}
EN=Early[,c("Description","InTerm_InList","X")]
```
```{r}
EN$Name=gsub("Early_","",EN$X)
```
```{r}
top_paths2 <- lapply(results_by_module, function(x) {
  
    x1=filter(x,ONTOLOGY=="BP")
    top10<- arrange(x1,p.adjust) %>%head(100)

 return(top10)
})


top_paths_df2 <- do.call(rbind, top_paths2)
top_paths_df2$Label <- rep(names(top_paths2), sapply(top_paths2, nrow))


# results_by_module
head(top_paths_df2)
```
```{r}
write.csv(top_paths_df2,"top_paths_df2.csv")
```


```{r}
top_paths <- lapply(results_by_module, function(x) {
  
    x1=filter(x,ONTOLOGY=="BP")
    top10<- arrange(x1,p.adjust) %>%head(2)

 return(top10)
})


top_paths_df <- do.call(rbind, top_paths)
top_paths_df$Label <- rep(names(top_paths), sapply(top_paths, nrow))


# results_by_module
head(top_paths_df)
```

```{r}
top_paths_df$Name=gsub("Module-","",top_paths_df$Label)
```

```{r}
top_paths_df<-top_paths_df[grep("NK|Tcell|Mono",top_paths_df$Name),]
```

```{r}
colnames(EN)<-c("Description","Count","Label","Name")
```


```{r}
Gene=rbind(top_paths_df[,c("Description","Count","Label","Name")],EN)
```

```{r}
subMK=results_by_module$`Module-MK`
head(subMK,100)
subMK2=subMK[grep("GO:0030168|GO:0070527",subMK$ID),]
subMK2$Label<-"MK"
subMK2$Name<-"MK"
```

```{r}
Gene=rbind(top_paths_df[,c("Description","Count","Label","Name")],EN)
Gene=rbind(subMK2[,c("Description","Count","Label","Name")],Gene)
```

```{r}
Gene$Name<-factor(Gene$Name,levels = c("ERY","MK", "STEM","Mono","Bcell","NK","Tcell"))
unique(Gene$Description)
```

```{r}
Gene$Description<-factor(Gene$Description,levels = c("regulation of ossification","biogenic amine metabolic process" ,"platelet aggregation","platelet activation","embryo development ending in birth or egg hatching","blood vessel development","myeloid leukocyte activation","response to lipopolysaccharide","regulation of innate immune response","positive regulation of cell adhesion","leukocyte mediated immunity","cell killing","leukocyte activation","T cell differentiation"))
```

```{r}
library(ggplot2)



background_df <- expand.grid(
  Description = unique(Gene$Description),
  Label = unique(Gene$Name)
)


background_df$fill <-1- (1:nrow(background_df)) %% 2


P1=ggplot() +
  geom_tile(data = background_df, aes(x = Description, y = Label, fill = as.factor(fill)), alpha = 0.5) +
  scale_fill_manual(values = c("white", "gray")) +
  geom_point(data = Gene, aes(x = Description, y = Name, size = Count),color="red") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  xlab('') +
  ylab('')+coord_flip()
P1
ggsave("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Main_Figure2/Late_enrich.pdf")
```
```{r}
ggsave("/home/maolp/Main_Gao_ScanpyProject20231130/HFB_Figure_Plot/Main_Figure2/Early_enrich.pdf")
```

